// lib/quotes.ts — Role-based motivational quotes for ZenFocus
import type { UserRole } from './storage';

export const STUDENT_QUOTES: string[] = [
  "Education is the passport to the future.",
  "The beautiful thing about learning is nobody can take it away from you.",
  "Study hard today, celebrate tomorrow.",
  "Your grades don't define you, but your effort does.",
  "A little progress each day adds up to big results.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Don't study to earn, study to learn.",
  "The expert in anything was once a beginner.",
  "It always seems impossible until it's done.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Don't wait for opportunity. Create it.",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "The secret of getting ahead is getting started.",
  "Education is not preparation for life; education is life itself.",
  "You don't have to be great to start, but you have to start to be great.",
  "Believe you can and you're halfway there.",
  "The only way to do great work is to love what you study.",
  "Your limitation—it's only your imagination.",
  "What seems hard now will one day be your warm-up.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Discipline is choosing between what you want now and what you want most.",
  "Study like there's no tomorrow because if you keep putting it off, there won't be.",
  "Focus on progress, not perfection.",
  "A year from now you'll wish you had started today.",
  "An investment in knowledge pays the best interest.",
  "The mind is not a vessel to be filled, but a fire to be kindled.",
  "Learning never exhausts the mind.",
  "There are no shortcuts to any place worth going.",
  "Success doesn't come from what you do occasionally, it comes from what you do consistently.",
  "Strive for progress, not perfection.",
  "Don't let what you cannot do interfere with what you can do.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Knowledge is power. Information is liberating.",
  "Hard work beats talent when talent doesn't work hard.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "Today a reader, tomorrow a leader.",
  "Education is the most powerful weapon you can use to change the world.",
  "The roots of education are bitter, but the fruit is sweet.",
  "Study without desire spoils the memory, and it retains nothing.",
  "I find that the harder I work, the more luck I seem to have.",
  "Genius is 1% inspiration and 99% perspiration.",
  "There is no substitute for hard work.",
  "The way to get started is to quit talking and begin doing.",
  "If you're going through hell, keep going.",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
  "Don't watch the clock; do what it does. Keep going.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "If people knew how hard I worked to get my mastery, it wouldn't seem so wonderful.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "Be so good they can't ignore you.",
  "The only person you are destined to become is the person you decide to be.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "Quality is not an act, it is a habit.",
  "Either you run the day, or the day runs you.",
  "Everything you've ever wanted is on the other side of fear.",
  "Perseverance is not a long race; it is many short races one after the other.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Start where you are. Use what you have. Do what you can.",
  "Nothing is impossible. The word itself says I'm possible.",
  "Fall seven times, stand up eight.",
  "Doubt kills more dreams than failure ever will.",
  "It does not matter how slowly you go as long as you do not stop.",
  "With the new day comes new strength and new thoughts.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "Be not afraid of going slowly; be afraid only of standing still.",
  "Your time is limited, so don't waste it living someone else's life.",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
  "In the middle of every difficulty lies opportunity.",
  "What we learn with pleasure we never forget.",
  "To learn, read. To know, write. To master, teach.",
  "Commit to learning. Every day. Every moment.",
  "The goal of education is not to increase the amount of knowledge but to create possibilities.",
  "You can never be overdressed or overeducated.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
  "The only thing that interferes with my learning is my education.",
  "Self-education is, I firmly believe, the only kind of education there is.",
  "Learning is a treasure that will follow its owner everywhere.",
  "The beautiful thing about learning is that no one can take it away from you.",
  "Once you stop learning, you start dying.",
  "Anyone who stops learning is old, whether at twenty or eighty.",
  "Study the past if you would define the future.",
  "It's not about being the best. It's about being better than you were yesterday.",
  "Your education is a dress rehearsal for a life that is yours to lead.",
  "The more I study, the more insatiable do I feel my genius for it to be.",
  "Keep calm and study on.",
  "Today's preparation determines tomorrow's achievement.",
  "Champions keep playing until they get it right.",
  "Every accomplishment starts with the decision to try.",
  "Winners are not people who never fail, but people who never quit.",
  "Difficult roads often lead to beautiful destinations.",
];

export const DEVELOPER_QUOTES: string[] = [
  "Code is like humor. When you have to explain it, it's bad.",
  "First, solve the problem. Then, write the code.",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
  "Clean code always looks like it was written by someone who cares.",
  "Simplicity is the soul of efficiency.",
  "Make it work, make it right, make it fast.",
  "The best error message is the one that never shows up.",
  "Programming isn't about what you know; it's about what you can figure out.",
  "The most disastrous thing you can ever learn is your first programming language.",
  "Code never lies, comments sometimes do.",
  "Fix the cause, not the symptom.",
  "Ship it, then iterate.",
  "The only way to learn a new programming language is by writing programs in it.",
  "Talk is cheap. Show me the code.",
  "Programs must be written for people to read, and only incidentally for machines to execute.",
  "Before software can be reusable it first has to be usable.",
  "The best code is no code at all.",
  "Debugging is twice as hard as writing the code in the first place.",
  "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
  "Software is a great combination between artistry and engineering.",
  "The function of good software is to make the complex appear simple.",
  "Don't comment bad code — rewrite it.",
  "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.",
  "It's not a bug; it's an undocumented feature.",
  "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code.",
  "You might not think that programmers are artists, but programming is an extremely creative profession.",
  "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.",
  "Code is read more often than it is written.",
  "The best thing about a boolean is even if you are wrong, you are only off by a bit.",
  "A good programmer looks both ways before crossing a one-way street.",
  "Experience is the name everyone gives to their mistakes.",
  "In theory, there is no difference between theory and practice. But in practice, there is.",
  "Every great developer you know got there by solving problems they were unqualified to solve.",
  "When I wrote this code, only God and I understood what I did. Now only God knows.",
  "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs.",
  "Walking on water and developing software from a specification are easy if both are frozen.",
  "Deleted code is debugged code.",
  "Java is to JavaScript what car is to carpet.",
  "One man's crappy software is another man's full-time job.",
  "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.",
  "Software and cathedrals are much the same — first we build them, then we pray.",
  "Real programmers count from 0.",
  "Weeks of coding can save you hours of planning.",
  "The computer was born to solve problems that did not exist before.",
  "Copy-and-paste is a design error.",
  "Don't worry if it doesn't work right. If everything did, you'd be out of a job.",
  "No code runs faster than no code.",
  "Premature optimization is the root of all evil.",
  "The best performance improvement is the transition from the nonworking state to the working state.",
  "Write code that writes code.",
  "Good code is its own best documentation.",
  "Coding like poetry should be short and concise.",
  "Simplicity is prerequisite for reliability.",
  "On two occasions I have been asked, 'Can you tell me what the machine will do?' I just say no.",
  "A language that doesn't affect the way you think about programming is not worth knowing.",
  "The sooner you start to code, the longer the program will take.",
  "Testing leads to failure, and failure leads to understanding.",
  "The most important property of a program is whether it accomplishes the intention of its user.",
  "Optimism is an occupational hazard of programming.",
  "Computers are fast; developers keep them slow.",
  "Beware of bugs in the above code; I have only proved it correct, not tried it.",
  "The art of programming is the art of organizing complexity.",
  "Controlling complexity is the essence of computer programming.",
  "The best code is the code you didn't write.",
  "A primary cause of complexity is that software vendors uncritically adopt almost any feature that users want.",
  "Software being 'Done' is like lawn being 'Mowed'.",
  "If you automate a mess, you get an automated mess.",
  "One of my most productive days was throwing away 1000 lines of code.",
  "The Web does not just connect machines, it connects people.",
  "Stay hungry, stay foolish, keep shipping.",
  "Build what matters. Delete what doesn't.",
  "Deep work creates deep products.",
  "Silent focus is the loudest productivity.",
  "Every great product started with one focused session.",
  "Ship it. Improve it. Repeat forever.",
  "The best time to refactor was yesterday. The next best time is now.",
  "Think twice, code once.",
  "Commit early, commit often.",
  "Legacy code is code without tests.",
  "Types are the best documentation.",
  "A bug is never just a mistake. It represents something bigger.",
  "Never trust a computer you can't throw out a window.",
  "Unix is simple. It just takes a genius to understand its simplicity.",
  "The Internet? Is that thing still around?",
  "Most good programmers do programming not because they expect to get paid, but because it is fun to program.",
  "Programming is thinking, not typing.",
  "Any application that can be written in JavaScript will eventually be written in JavaScript.",
  "In programming, the hard part isn't solving problems, but deciding what problems to solve.",
  "Good developers write good code. Great developers delete bad code.",
  "Refactoring is just paying off technical debt.",
  "If you think good architecture is expensive, try bad architecture.",
  "Software is eating the world.",
  "Move fast and break things. Then fix the broken things.",
  "Done is better than perfect.",
  "Focus on the user and all else will follow.",
  "Build for the long term.",
  "Clarity of mind creates clarity of code.",
  "Stay in flow. The magic happens here.",
  "The best code is written in a calm mind.",
  "Build. Ship. Repeat.",
  "One task. Full focus. Ship it.",
];

export function getRandomQuote(role?: UserRole): string {
  const pool = role === 'student' ? STUDENT_QUOTES : DEVELOPER_QUOTES;
  return pool[Math.floor(Math.random() * pool.length)];
}
